### ISSUE TITLE
Corrade/Utility/Arguments.h does not compile with libc++ version 19.1.7-1 because of missing include file vector

### ISSUE THREAD

**Issue by werto87** [mosra/corrade#200]
This code does not compile withlibc++ version 19.1.7-1 

```c++
#include <Corrade/Utility/Arguments.h>

int
main ()
{
  return 0;
}
```

I get the error:

include/Corrade/Utility/Arguments.h:326:21: error: no template named 'vector' in namespace 'std'
         static std::vector<std::string> environment();

If I put
```c++
 #include <vector>
```
  infront of 
```c++
#include <Corrade/Utility/Arguments.h>
```
it compiles
```c++
#include <vector>
// left blanc to prevent sorting from clang format
#include <Corrade/Utility/Arguments.h>

int
main ()
{
  return 0;
}
```
I think you need to add 
```c++
#include <vector>
```
in Corrade/Utility/Arguments.h

**Comment by mosra** [comment]
There's a `Utility/StlForwardVector.h` include used instead, which includes a forward declaration of `std::vector` to speed up compilation. 

There was a change for libc++ 19.1, where it moved the forward declaration to a different place, 5527f79497914f5aa779914058596c3dc388059d (November 2024) adapted to that, and I just tested with 19.1.7 and it still works correctly. 

Is it possible that you're using an older revision, or even the ancient `v2020.06` tag? (Sorry about being unable to create a new tagged release since then, see #197 for details.)

**Comment by werto87** [comment]
Sorry for leaving out the version. I am using v2020.06. I will try to package a new version using conan. Thank you.
