### ISSUE TITLE
Utility: FileWatcher does not compile on gcc 5.4.0

### ISSUE THREAD

**Issue by xqms** [mosra/corrade#54]
Got a compiler error:

```
/home/user/schwarzm/install/corrade/src/Corrade/Utility/FileWatcher.cpp:59:14: error: function ‘Corrade::Utility::FileWatcher& Corrade::Utility::FileWatcher::operator=(Corrade::Utility::FileWatcher&&)’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
 FileWatcher& FileWatcher::operator=(FileWatcher&&)
```

gcc version:
```
# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
```

I did a quick bisect and the problem was introduced in e573f593e703e542639feacc174cbaf9fcc00540.

**Comment by mosra** [comment]
Hi, thanks for the report (and thanks for going an extra way with the bisect)! :+1: 

I did a similar workaround for Clang 3.8 in https://github.com/mosra/corrade/commit/d26b546a279e039fa9b4e6de394ef3a314234abd and assumed that this, having it worked on the venerable GCC 4.7, would work on all newer GCCs as well (it does work on 8 again)...

I'll look around if I have some GCC 5 around to test on, in the meanwhile can you try removing the `noexcept` specifier from the operator=? That should make it work.

**Comment by xqms** [comment]
Works without the `noexcept` :+1:

**Comment by mosra** [comment]
Just tested locally with GCC 5.5 and there it works. Turns out to be a bug/non-conformance in libstdc++ < 5.5: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58265 Now I'm not sure why it worked on 4.7 (probably the compiler just didn't care back then). 

I pushed a fix in c32b0967b8cb544d5c5d48522704eaeb99559028 (it's the `next` branch at the moment, not `master` yet). Could you verify it works, please? Thank you!

**Comment by mosra** [comment]
Thanks for the confirmation! Merged into master now.

**Comment by xqms** [comment]
That was quick, thanks! :-)
